### ISSUE TITLE
Question:  Is halyard.js a possible alternative for QVX?

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/halyard.js#4]
### Description

Considering what it takes to build a qvx connector, the concept of using halyard.js to create a data connection for Qlik Sense is something I've started to wonder is possible.  Where I'm getting stuck is the part of the data connector that surfaces the ui in the Qlik Sense client.  

If that part isn't part of qvx requirement, is it possible that a data connector could be created with halyard?

**Comment by StefanEnberg** [comment]
Interesting idea! halyard.js are only using the native connectors like local-folder or web-file. If the raw-data pushed through halyard.js then it will be inline loaded in the script without the need for a connector. 

It would be possible to build your own halyard.js connectors to abstract away the connector logic but they would need to use inline load. This would require all reloads to be done with halyard.

**Comment by goldbergjeffrey** [comment]
I guess the question becomes can I package that into something that is available through the add data / load editor ui?  Inline load for lots of records isn't great, but something less complex than qvx is very intriguing.

**Comment by StefanEnberg** [comment]
We are currently not planning on adding that kind of functionality to halyard.js. We have another approach that can make it easier to create connector and that is https://github.com/qlik-oss/core-file-connectivity-service. Also the new connectors API will make it easier compared to qvx https://www.qlikcore.com/docs/services/qix-engine/apis/data-loading/introduction/
